# Generated by Django 3.1.2 on 2020-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='remark',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
