# Generated by Django 3.1.2 on 2020-10-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='remark',
        ),
    ]
